version: '5'

services:
  db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=crm-go
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    ports:
      - 3309:3306

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '4999:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data-go-crm:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data-go-crm:
